version: '3.7'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senocak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" # for debezium
    #OR
    #command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
    networks:
      - ops
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass senocak
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - ops
  memcached:
    image: memcached:alpine
    restart: unless-stopped
    ports:
      - "11211:11211"
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60
    networks:
      - ops
volumes:
  db-data:
  redis-data:
networks:
  ops: